name: default
duration_sec: 20
tick_sec: 1.0
emitters:
  - name: csv
    eps: 5
    args:
      partial_ratio: 0.2

  - name: json
    eps: 5
    args:
      partial_ratio: 0.2

  - name: minimal
    eps: 5

  - name: noise
    eps: 5
    args:
      chaos: 0.3

  - name: syslog
    eps: 5
    args:
      partial_ratio: 0.1
