#!/usr/bin/env bash
set -Eeuo pipefail

PROM_URL="${PROM_URL:-http://127.0.0.1:9090}"
LOKI_URL="${LOKI_URL:-http://127.0.0.1:3100}"
WINDOW="${WINDOW:-15m}"

SCENARIO_ID="${SCENARIO_ID:-}"
if [[ -z "${SCENARIO_ID}" ]] && [[ -f data/e2e/last_scenario_id ]]; then
  SCENARIO_ID="$(cat data/e2e/last_scenario_id)"
fi
[[ -n "${SCENARIO_ID}" ]] || { echo "ERR: Brak SCENARIO_ID (podaj env SCENARIO_ID=... lub uruchom najpierw make e2e)"; exit 2; }

mkdir -p data/reports
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT="data/reports/e2e-${SCENARIO_ID}-${STAMP}.md"

jq_ensure() { command -v jq >/dev/null || { echo "ERR: wymagany jq"; exit 3; }; }
curl_ensure(){ command -v curl >/dev/null || { echo "ERR: wymagany curl"; exit 3; }; }
jq_ensure; curl_ensure

# Prometheus – dane
INGESTED_JSON=$(curl -fsS -G "$PROM_URL/api/v1/query" \
  --data-urlencode "query=sum by (emitter) (increase(logops_ingested_total[$WINDOW]))")
ACCEPTED_JSON=$(curl -fsS -G "$PROM_URL/api/v1/query" \
  --data-urlencode "query=sum by (emitter) (increase(logops_accepted_total[$WINDOW]))")
PARSE_RATE_JSON=$(curl -fsS -G "$PROM_URL/api/v1/query" \
  --data-urlencode "query=100 * ( sum(rate(logops_parse_errors_total[$WINDOW])) / ( sum(rate(logops_parse_errors_total[$WINDOW])) + sum(rate(logops_accepted_total[$WINDOW])) ) )")
P95_JSON=$(curl -fsS -G "$PROM_URL/api/v1/query" \
  --data-urlencode "query=histogram_quantile(0.95, sum by (le) (rate(logops_batch_latency_seconds_bucket[$WINDOW])))")
ALERTS_JSON=$(curl -fsS -G "$PROM_URL/api/v1/query" \
  --data-urlencode 'query=ALERTS{alertstate="firing"}')

# Loki – liczba linii i rozkład level
LOKI_LINES_JSON=$(curl -fsS -G "$LOKI_URL/loki/api/v1/query" \
  --data-urlencode "query=sum(count_over_time({app=\"logops\",source=\"ingest\",scenario_id=\"$SCENARIO_ID\"}[$WINDOW]))")
LOKI_LEVEL_JSON=$(curl -fsS -G "$LOKI_URL/loki/api/v1/query" \
  --data-urlencode "query=sum by (level) (rate({app=\"logops\",source=\"ingest\",scenario_id=\"$SCENARIO_ID\"}[$WINDOW]))")

# Małe helpery do tabel
tbl_pm() { # $1 = JSON z Prom /api/v1/query; drukuj "name: value"
  echo "$1" | jq -r '
    if .data.result|length==0 then "(brak)" else
      .data.result[] | "\((.metric.emitter // .metric.level // .metric.alertname // "all")): \(.value[1])"
    end'
}

p95_val=$(echo "$P95_JSON" | jq -r '.data.result[0]?.value[1] // "0"')
parse_rate=$(echo "$PARSE_RATE_JSON" | jq -r '.data.result[0]?.value[1] // "0"')
lines=$(echo "$LOKI_LINES_JSON" | jq -r '.data.result[0]?.value[1] // "0"')

{
  echo "# LogOps E2E Report"
  echo
  echo "- Scenario ID: \`$SCENARIO_ID\`"
  echo "- Okno: \`$WINDOW\`"
  echo "- Czas: \`$STAMP\` (UTC)"
  echo
  echo "## Prometheus"
  echo "**Ingested increase by emitter**"
  tbl_pm "$INGESTED_JSON"
  echo
  echo "**Accepted increase by emitter**"
  tbl_pm "$ACCEPTED_JSON"
  echo
  echo "**p95 ingest batch latency:** \`$p95_val s\`"
  echo
  echo "**Parse error rate (global):** \`$parse_rate %\`"
  echo
  echo "**Active alerts (firing):**"
  tbl_pm "$ALERTS_JSON"
  echo
  echo "## Loki"
  echo "**Lines for scenario (\`$SCENARIO_ID\`):** \`$lines\`"
  echo
  echo "**Rate by level**"
  tbl_pm "$LOKI_LEVEL_JSON"
  echo
  echo "_Generated by obs_report.sh_"
} > "$OUT"

echo "Raport zapisany → $OUT"
